In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3,4,5]

In [3]:
array_np=np.array(list_1)

In [5]:
array_np ,type(array_np)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [6]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
print (np.ones(5))

[1. 1. 1. 1. 1.]


In [14]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [15]:
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.linspace(0,1,10),np.linspace(0,1,10)[1]

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

In [18]:
vector_array=np.arange(25)

In [19]:
vector_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
matrix_array=vector_array.reshape(5,5)
matrix_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
vector_array.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [26]:
np.arange(1,26).reshape(5,5)/10

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

In [31]:
print(np.linspace(0,24,25).reshape(5,5))
print("Step size is :",np.linspace(0,24,25)[1])

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
Step size is : 1.0


In [32]:
#arange() takes 3rd argument as step size
#linespace() takes 3rd argument as no of points we want


In [33]:
np.random.rand(1)

array([0.93622828])

In [34]:
np.random.rand(7,5)

array([[0.35165482, 0.02476004, 0.01714461, 0.99926372, 0.93346255],
       [0.77554778, 0.89747404, 0.16701968, 0.37354484, 0.23541955],
       [0.83738714, 0.34383202, 0.02304228, 0.82526709, 0.21189978],
       [0.97602758, 0.05169184, 0.63826411, 0.7912588 , 0.80815242],
       [0.20123981, 0.13375569, 0.53248465, 0.28035804, 0.07282497],
       [0.42458115, 0.51065614, 0.25311706, 0.87664033, 0.93599919],
       [0.83217208, 0.1620101 , 0.50737113, 0.3425414 , 0.2841379 ]])

In [35]:
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [38]:
array_2d=np.arange(30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [39]:
array_2d[3:,2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [41]:
array_2d[5,4]

29

In [43]:
array_2d[:3,1:2]

array([[ 1],
       [ 6],
       [11]])

In [44]:
array_2d[2]

array([10, 11, 12, 13, 14])

In [45]:
array_2d[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
array_2d.sum()

435

In [48]:
print(array_2d.sum(axis=0))

[75 81 87 93 99]


In [49]:
print(array_2d.sum(axis=1))

[ 10  35  60  85 110 135]


In [50]:
array_2d.std()

8.65544144839919

In [54]:
mask_mod_3 =0!=array_2d%3

In [56]:
array_2d[mask_mod_3]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])